spring:
  application:
    name: item-service
    
    #连接rabbitmq中心   
    rabbitmq:
      host: 192.168.64.140  
      port: 5672
      username: admin
      password: admin
    
 #禁止配置中心的配置将客户端配置覆盖掉    
  cloud:
    config:
      override-none: true
 
    
server:
  port: 8001

#注册eureka
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      
   
